neviaumi/resume.json

- docs/js/sections/resume-skills.element.js
> ISSUE-508: master skill shhould highlight as primary by default

- docs/resume.json
> ISSUE-506: update projects list

- docs/js/sections/resume-work.element.js
> ISSUE-511: move position to company name together

- .idea/misc.xml
- docs/js/sections/resume-application.element.js
- docs/js/sections/resume-summary.element.js
- docs/resume.json
- src/build-pdf.js
> ISSUE-530: show expected salary when available

- docs/js/sections/resume-application.element.js
- docs/resume.json
> ISSUE-568: hide role responsibilities when empty

- docs/resume.json
> ISSUE-570: update wording by feedback from chatgpt

- README.md
- docs/resume.json
> GH-606: upgrade resume

- docs/js/sections/resume-application.element.js
> GH-608: include date of availability

- docs/resume.json
> GH-613: update my summary to include what i looking for

- llm/src/llm/introduction.py
> GH-647: update introduction

- .github/tests/test-deploy-gh-page.json
- .github/workflows/deploy-gh-page.yml
- .husky/pre-push
- docs/resume.json
- package.json
- scripts/build.sh
- scripts/setup.sh
- scripts/test.sh
> GH-514: update gp-page deployment

- .github/workflows/deploy-gh-page.yml
> GH-514: fix missing permission error

- docs/resume.json
> GH-661: include llm in made-in-uk project

- .idea/misc.xml
- .idea/resume.json.iml
- Dockerfile
- llm/src/llm/introduction.py
> GH-684: skip empty feedback

- README.md
> GH-686: fixing the link in readme was outdated

- .github/workflows/deploy-gh-page.yml
> GH-689: fix deployment script

- Dockerfile
> GH-513: fix docker

- package-lock.json
- package.json
- vite.config.js
> GH-513: fix vite build

- src/main.css
- src/roboto.css
- src/sections/skill-badge.element.js
> GH-705: use Roboto as default font family

- README.md
- scripts/test.sh
- src/json-resume.element.js
- src/sections/skill-badge.element.js
- vite.config.js
> GH-700: fix the color tone and build

- docs/sample-jd/loomery.md
- src/job-description.js
- src/look-for-jobs/cover-letter.js
- src/look-for-jobs/linkedin-job-search-filters.js
- src/open-ai.js
- src/prepare-interview/why-are-you-the-best-candidate-for-this-job.js
> GH-737: script to generate cover-letter and include loomery to sample jd

- src/prepare-interview/final-questions.js
- src/prepare-interview/introduction.js
- src/prepare-interview/why-are-you-the-best-candidate-for-this-job.js
> GH-741: generate final questions to ask in end of interview

- src/prepare-interview/final-questions.js
- src/prepare-interview/introduction.js
this close of #746
Updated the follow-up question format to include explanations for each question, providing more context for their relevance. This change aims to improve the clarity and depth of interview preparation.
> GH-746: Enhance follow-up question details in interview tool

- docs/sample-jd/fonoa.md
> GH-758: include fonoa in sample jd

- Dockerfile
- public/resume.base.json
- src/look-for-jobs/cover-letter.js
> GH-762: include word count on cover letter generation

- .github/dependabot.yml
- Dockerfile
- package.json
> GH-764: downgrade and disable of playwright

- .github/dependabot.yml
> GH-764: fix synax error on dependabot.yml

- public/resume.base.json
> GH-771: include python in project keyword

- src/apply-for-job/transform-jd-to-md.js
this fix #780
Add an else branch to log the company's core values only if they exist, ensuring the message gets printed correctly. This prevents the log from missing when core values are present and improves the clarity of our debug output.
> GH-780: Fix company core value log message condition

- docs/sample-jd/amal-initiative.md
- src/apply-for-job/cord-intro-message.js
- src/apply-for-job/volunteering-intro-message.js
- src/job-description.js
- src/resume.js
this close #782
Added a new function to generate introductory messages for volunteering positions using OpenAI. Integrated sample job descriptions and support for personal website links. Enhanced resume handling by adding functions to retrieve personal websites.
> GH-782: Add volunteer intro message generation feature

- eslint.config.js
this close #784
include package.json linting configuration
> GH-784: update eslint.config.js

- .fleet/settings.json
- public/resume.base.json
this close #793
Added a setting for automatic formatting on save to maintain code consistency. Reformatted arrays in the resume JSON file to enhance readability and maintain a consistent structure across different sections. Improved visual clarity with expanded array elements.
> GH-793: Enable format on save and reformat JSON arrays

- public/resume.base.json
this close #809
Included a detailed reference from Henrique Gabriel Rodrigues Cordeiro, a PlayStation Software Engineer, highlighting technical expertise, teamwork, and collaborative qualities. This enhances the resume's credibility and professional reputation.
> GH-809: Add new professional reference to resume JSON file

- .github/dependabot.yml
- package-lock.json
- package.json
- public/resume.base.json
- src/resume-html/sections/resume-about.element.js
- src/resume-html/sections/resume-header.element.js
- src/resume-html/sections/resume-projects.element.js
- src/sync-from-portfolio/load-html.js
- src/sync-from-portfolio/personal-summary.js
- src/sync-from-portfolio/project-description.js
this fix #860
Introduced JavaScript modules to sync portfolio data for dynamic generation of resume content, including personal summaries, project descriptions, and highlights. Updated UI elements for consistency, improved the "About Me" link text, and standardized project URLs. Enhanced resume summary and added detailed portfolio information to improve clarity and alignment with user goals.
> GH-860: Add portfolio data sync and enhance resume structure

- vite.config.js
this fix #874
This update specifies entry points and formats for the library build. It ensures compatibility with ES modules and improves the build process for `resume-html`.
> GH-874: Add library mode configuration to build settings

- index.html
- src/resume-html/json-resume.element.js
this close #881
Extracted container wrapping into a reusable function and split resume rendering into separate methods for improved code readability and maintainability. Added error handling to display meaningful messages when resume loading fails. Dynamically load base or tailored resume based on environment configuration.
> GH-881: Refactor resume rendering logic to improve modularity
